---
title: "powerplant"
format: revealjs
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
powerplantcsv <- read_csv("Power_Plants_in_the_U.S..csv") 

#Power Generating in Daily Production

powerplantcsv |>
  summarise(combinepower = sum(Total_MW)*365)

Total_MW 
```
```{r}
powerTX <- powerplantcsv |>
  select(FID,Longitude, Latitude, City, County, State, PrimSource, Total_MW) |>
  filter(State == 'Texas') |>
  summarise(count = n(), totalpower = sum(Total_MW), .by = c("County",'State')) |>
  mutate(county = County)

powerTX

```

```{r}
TXpop <- read.csv("TXPOP.csv") |>
  mutate(
    Counties = gsub("^\\.", "", Counties), # Remove leading dot
    Counties = gsub(" County.*$", "", Counties) # Remove " County" and everything after
  ) |>
  mutate(population = as.numeric(gsub(",", "", Estimates)))|>
  mutate(county = Counties) |>
  select(county, population)


GDPcounty <- read.csv("gdpallcounties.csv") |>
  mutate(fips = FIPS) |>
  select(fips, GDP_ALL)

fips <- read.csv("county_fips.csv")

fipsTX <- fips |>
  filter(state_name == "Texas") |>
  select(fips, county_name) |>
  mutate(county_name = gsub(" County.*$", "", county_name))

gdpTXcounty <- merge(GDPcounty, fipsTX, .by = c('fips'))
```



```{r}
TXpop
gdpTXcounty
powerTX 
```
```{r}
powerTX |>
  summarise(ALLPOWER = sum(totalpower))
```


```{r}
TXcountyPower <- TXpop |>
  mutate(pop_prop = population/sum(population)) |>
  mutate(electric_prop = round((pop_prop*149783.2),3)) |>
  select(county, population, electric_prop) |>
  arrange(desc(electric_prop))


TXcountyPowergdp <- gdpTXcounty |>
  mutate(GDP_prop = GDP_ALL/sum(GDP_ALL)) |>
  mutate(electric_prop = round((GDP_prop*149783.2),3)) |>
  select(county_name, GDP_ALL, electric_prop) |>
  arrange(desc(electric_prop)) |>
  mutate(County = county_name) 
```

```{r}
TXcountyPower

dfdeficit <- merge(powerTX, TXcountyPower, all = TRUE) |>
  select(county, count, totalpower, electric_prop) |>
  mutate_all(~replace(., is.na(.), 0)) |>
  mutate(deficit = totalpower - electric_prop) |>
  arrange(desc(deficit))
```

```{r}
write_csv(dfdeficit,"deficit.csv")
```


```{r}
powerplantcsv |>
  filter(State == "Texas") |>
  select(Longitude, Latitude, Total_MW, County, State, PrimSource)
```


```{r}
nicholas <- read_csv("NICHOLAS.csv")
```








